[vim]
any = true

[assert]
any = true

[describe]
any = true

[after_each]
any = true

[it]
any = true

[type]
any = true

[error]
any = true

[pairs]
any = true

[ipairs]
any = true

[pcall]
any = true

[tonumber]
any = true

[tostring]
any = true

[string]
any = true

[math]
any = true

[table]
any = true

[io]
any = true

[debug]
any = true

[require]
any = true
